# Basic colors
foreground              #e2e2e9
background              #111318
selection_foreground    #dae2f9
selection_background    #3e4759

# Cursor colors
cursor                  #aac7ff
cursor_text_color       #0a305f

# URL underline color when hovering with mouse
url_color               #ddbce0

# Kitty window border colors
active_border_color     #aac7ff
inactive_border_color   #44474e
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #d6e3ff
active_tab_background   #284777
inactive_tab_foreground #c4c6d0
inactive_tab_background #1e2024
tab_bar_background      #111318

# Colors for marks
mark1_foreground #0a305f
mark1_background #aac7ff
mark2_foreground #283141
mark2_background #bec6dc
mark3_foreground #3f2844
mark3_background #ddbce0

# The 16 terminal colors
# black
color0 #44474e
color8 #8e9099

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #aac7ff
color10 #d6e3ff

# yellow
color3  #ddbce0
color11 #fad8fd

# blue
color4  #bec6dc
color12 #dae2f9

# magenta
color5  #284777
color13 #415f91

# cyan
color6  #3e4759
color14 #573e5c

# white
color7  #c4c6d0
color15 #e2e2e9
