$primary_paletteKeyColor = 4b8358
$secondary_paletteKeyColor = 687c6a
$tertiary_paletteKeyColor = 537e87
$neutral_paletteKeyColor = 737872
$neutral_variant_paletteKeyColor = 717970
$background = 030503
$onBackground = dfe4dc
$surface = 030503
$surfaceDim = 030503
$surfaceBright = 0f110f
$surfaceContainerLowest = 020302
$surfaceContainerLow = 060806
$surfaceContainer = 070a07
$surfaceContainerHigh = 0b0d0b
$surfaceContainerHighest = 0e100e
$onSurface = dfe4dc
$surfaceVariant = 121411
$onSurfaceVariant = c1c9bf
$inverseSurface = dfe4dc
$inverseOnSurface = 2d322c
$outline = 8b938a
$outlineVariant = 414941
$shadow = 000000
$scrim = 000000
$surfaceTint = 112d19
$primary = 99d4a3
$onPrimary = 003918
$primaryContainer = 17512b
$onPrimaryContainer = b4f1bd
$inversePrimary = 326941
$secondary = b7ccb7
$onSecondary = 233426
$secondaryContainer = 3d5040
$onSecondaryContainer = d3e8d2
$tertiary = a2ced8
$onTertiary = 01363e
$tertiaryContainer = 6c98a1
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = b4f1bd
$primaryFixedDim = 99d4a3
$onPrimaryFixed = 00210c
$onPrimaryFixedVariant = 17512b
$secondaryFixed = d3e8d2
$secondaryFixedDim = b7ccb7
$onSecondaryFixed = 0e1f12
$onSecondaryFixedVariant = 394b3b
$tertiaryFixed = bdeaf5
$tertiaryFixedDim = a2ced8
$onTertiaryFixed = 001f25
$onTertiaryFixedVariant = 204d56
$term0 = 080808
$term1 = 769e00
$term2 = 92de89
$term3 = b9f796
$term4 = 81b697
$term5 = c6a844
$term6 = 9bd7a3
$term7 = d3dbc9
$term8 = 9fa597
$term9 = 85b900
$term10 = 97f38f
$term11 = daffc4
$term12 = abc8b0
$term13 = cec06b
$term14 = a8ebae
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = e3e4c5
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = bad799
$yellow = e1f8d2
$green = abf0b4
$teal = aeeec4
$sky = a1ebc4
$sapphire = 80d8b3
$blue = 64cfb1
$lavender = 89dcc6
$klink = 199977
$klinkSelection = 199977
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 79bc2a
$kneutralSelection = 79bc29
$kpositive = 41bf6e
$kpositiveSelection = 42bf6e
$text = dfe4dc
$subtext1 = c1c9bf
$subtext0 = 8b938a
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161615
$surface2 = 121211
$surface1 = 0c0e0c
$surface0 = 050705
$base = 000100
$mantle = 000100
$crust = 000100
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
